### PR TITLE
Some mosltly empty files for actioning by people who know stuff and a map for an imaginary information landscape

### PR DESCRIPTION
**Pull request by andywootton**

### CODE REVIEW

**Comment by SecondeJK** [comment]
Can we merge this please? I guess if you want CRs you'll need to assign a team etc

**Comment by SecondeJK** [comment]
Magic! thanks @LimeBlast

**Comment by LimeBlast** [comment]
I've merged it in, because it's an initial commit and I'm here - but I'm not sure who's best to look after this in the long term.

**Comment by andywootton** [comment]
Thanks. At this stage, I'm just throwing stuff up so people can tell me how/why I'm wrong.

**Pull request merged**
